Script started on Sun 09 Dec 2018 01:58:17 PM PST
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ make
gcc -ansi -std=c99 -Wall -c ImageList.c -o ImageList.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c MovieIO.c -o MovieIO.o
gcc -ansi -std=c99 -Wall -c MovieLab.c -o MovieLab.o 
gcc -ansi -std=c99 -Wall -c Movie.c -o Movie.o
gcc -ansi -std=c99 -Wall -c IterativeFilter.c -o IterativeFilter.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
ar rc libFilter.a DIPs.o
ranlib libFilter.a
gcc -Wall ImageList.o FileIO.o Image.o MovieIO.o MovieLab.o Movie.o IterativeFilter.o  -g -DDEBUG -lm -L. -lFilter -o MovieLab
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ make~eecs22/bin/yay -s 480x270 sample.yuv[22Gvalgrind ./MovieLab -reverse -m mouse.yuv -f 50 -o sample.yuv -s 480x270[22G~eecs22/bin/yay -s 480x270 sample.yuv[K[22Gvalgrind ./MovieLab -reverse -m mouse.yuv -f 50 -o sample.yuv -s 480x270[22G[9P[85G[22Gcd hw5[K[22Gls[Kcd hw5[22G./MovieLab -reverse -m mouse.yuv -f 50 -o sample.yuv -s 480x270[22G[9@valgrind [94G[22G~eecs22/bin/yay -s 480x270 sample.yuv[K[22Gmake[K[K./M./[K[K[KMovieLab -i HSSOE.ppm -o a[Ksample.yuv -start= - [K0 -end= 5 -step= 0.5 -hue
The movie file sample.yuv has been written successfully!
11 frames are written to the file sample.yuv in total.
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ ./MovieLab -i HSSOE.ppm -o sample.yuv -start= 0 -end= 5 -step= 0.5 -huem[P[P[P[P[P[P[P[P[P[P[P[P[1@-[1@m [1@ [1@h[1@u[1@e[1@.[1@y[1@u[1@v -o sample.yuv -start= 0[P[P[P[P[P[P[P[P[P[1@-[1@f [1@ [1@7[1@3 [1@  - [P-end= 5 -step= 0.5 -hue[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K-s 300x200 -reverse
The movie file hue.yuv has been read successfully!
The movie file sample.yuv has been written successfully!
73 frames are written to the file sample.yuv in total.
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ ./MovieLab -m hue.yuv -o sample.yuv -f 73 -s 300x200 -reverse[34Gi HSSOE.ppm -o sample.yuv -start= 0 -end= 5 -step= 0.5 -hue[K[K[Ksaturate
The movie file sample.yuv has been written successfully!
11 frames are written to the file sample.yuv in total.
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ ./MovieLab -i HSSOE.ppm -o sample.yuv -start= 0 -end= 5 -step= 0.5 -saturate -reverse
The movie file sample.yuv has been written successfully!
11 frames are written to the file sample.yuv in total.
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ make l[Kclean
rm -f *.o *.a MovieLab `find . -name '*.ppm' ! -name 'HSSOE.ppm'`
rm -f `find . -name '*.yuv' ! -name 'hue.yuv' ! -name 'mouse.yuv' ! -name 'reverse.yuv'`
]0;jlaron@zuma:~/hw5[jlaron@zuma ~/hw5]$ exit
exit

Script done on Sun 09 Dec 2018 02:01:41 PM PST
